### ISSUE TITLE
JPEG_CFR_CEOCF, JPEG_CFR_CHPDF bit definitions in stm32h745xx.h are probably incorrect.

### ISSUE THREAD

**Issue by cos-public** [STMicroelectronics/cmsis-device-h7#17]
Instead
#define JPEG_CFR_CEOCF_Pos              (4U)
#define JPEG_CFR_CHPDF_Pos              (5U)

it should be 
#define JPEG_CFR_CEOCF_Pos              (5U)
#define JPEG_CFR_CHPDF_Pos              (6U)

according to the spec
<img width="604" alt="Annotation 2024-10-13 202038" src="https://github.com/user-attachments/assets/99ed90d1-179b-4b21-93cf-9b942f1dd542">

**Comment by ASEHSTM** [comment]
Hello @cos-public,

Thank you for your report.
ST Internal Reference: 194796

With Regards,

**Comment by ASEHSTM** [comment]
Fixed in e4d57d6edc39f35aced298732829fc2a5e6a8a71
